version: "3.9"

services:
  nginx_stable:
    image: mysql:8.0.30
    container_name: mysql8
    volumes:
      - /opt/docker-compose/mysql/data:/var/lib/mysql
      - /opt/docker-compose/mysql/conf:/etc/mysql/conf.d
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456a
      - TZ=Asia/Shanghai