version: "3.9"

services:
  redis_01:
    # image: redis:7.0.2
    image: redis
    container_name: redis_01
    # restart: always
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    volumes:
      - /opt/docker-compose/redis-cluster/redis01/conf:/etc/redis
      - /opt/docker-compose/redis-cluster/redis01/data:/data
      - /opt/docker-compose/redis-cluster/redis01/log:/log
    ports:
      - 7001:7001
    environment:
      TZ: "Asia/Shanghai"
    # network_mode: "host"
    # networks:
    #   - redis_cluster_net

  redis_02:
    image: redis
    container_name: redis_02
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    volumes:
      - /opt/docker-compose/redis-cluster/redis02/conf:/etc/redis
      - /opt/docker-compose/redis-cluster/redis02/data:/data
      - /opt/docker-compose/redis-cluster/redis02/log:/log
    ports:
      - 7002:7002
    environment:
      TZ: "Asia/Shanghai"
    # network_mode: "host"
    # networks:
    #   - redis_cluster_net

  redis_03:
    image: redis
    container_name: redis_03
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    volumes:
      - /opt/docker-compose/redis-cluster/redis03/conf:/etc/redis
      - /opt/docker-compose/redis-cluster/redis03/data:/data
      - /opt/docker-compose/redis-cluster/redis03/log:/log
    ports:
      - 7003:7003
    environment:
      TZ: "Asia/Shanghai"
    # network_mode: "host"
    # networks:
    #   - redis_cluster_net

  redis_04:
    image: redis
    container_name: redis_04
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    volumes:
      - /opt/docker-compose/redis-cluster/redis04/conf:/etc/redis
      - /opt/docker-compose/redis-cluster/redis04/data:/data
      - /opt/docker-compose/redis-cluster/redis04/log:/log
    ports:
      - 7004:7004
    environment:
      TZ: "Asia/Shanghai"
    # network_mode: "host"
    # networks:
    #   - redis_cluster_net

  redis_cluster:
    image: redis
    depends_on:
      - redis_01
      - redis_02
      - redis_03
      - redis_04
    container_name: redis_cluster
    command: /bin/bash -c "redis-cli --cluster create 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 --cluster-replicas 0"
    environment:
      TZ: "Asia/Shanghai"
    # networks:
    #   - redis_cluster_net
    network_mode: "host"

# networks:
#   redis_cluster_net:
# network_mode: "host"


#  redis 官网提示应该使用 network_mode: "host"
# https://redis.io/docs/manual/scaling/