version: "3.9"

services:
  redis_01:
    # image: redis:7.0.2
    image: redis
    container_name: redis_01
    # restart: always
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    volumes:
      - /opt/docker-compose/redis-sentinel/redis01/conf:/etc/redis
      - /opt/docker-compose/redis-sentinel/redis01/data:/data
      - /opt/docker-compose/redis-sentinel/redis01/log:/log
    ports:
      - 7001:7001
      - 3001:3001
    environment:
      TZ: "Asia/Shanghai"
    networks:
      redis_cluster_net:
        aliases:
          - redis-master

  redis_02:
    image: redis
    depends_on:
      - master
    container_name: redis_02
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    volumes:
      - /opt/docker-compose/redis-sentinel/redis02/conf:/etc/redis
      - /opt/docker-compose/redis-sentinel/redis02/data:/data
      - /opt/docker-compose/redis-sentinel/redis02/log:/log
    ports:
      - 7002:7002
      - 3002:3002
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - redis_cluster_net

  redis_03:
    image: redis
    depends_on:
      - master
    container_name: redis_03
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    volumes:
      - /opt/docker-compose/redis-sentinel/redis03/conf:/etc/redis
      - /opt/docker-compose/redis-sentinel/redis03/data:/data
      - /opt/docker-compose/redis-sentinel/redis03/log:/log
    ports:
      - 7003:7003
      - 3003:3003
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - redis_cluster_net

  redis_04:
    image: redis
    depends_on:
      - master
    container_name: redis_04
    command: 
      - /bin/bash -c "redis-server /etc/redis/redis.conf"
      # - redis-cli --cluster create redis_cluster_net:7001 redis_cluster_net:7002 redis_cluster_net:7003 redis_cluster_net:7004 --cluster-replicas 1
    volumes:
      - /opt/docker-compose/redis-sentinel/redis04/conf:/etc/redis
      - /opt/docker-compose/redis-sentinel/redis04/data:/data
      - /opt/docker-compose/redis-sentinel/redis04/log:/log
    ports:
      - 7004:7004
      - 3004:3004
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - redis_cluster_net

networks:
  redis_cluster_net:

# network_mode: "host"